<section class="mt-3 card card-body">
    <h1>Novo Curso</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3">

                <label for="periodo">Periodo</label>
                <input name="periodo" type="text" id="periodo" class="form-control mb-3">

                <label for="professor">Professor</label>
                <input name="professor" type="text" id="professor" class="form-control mb-3">

                <label for="laboratorio">Laboratorio</label>
                <input name="laboratorio" type="text" id="laboratorio" class="form-control mb-3">

                <button class="btn btn-primary">Pronto</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>