<section class="mt-3 card card-body">
    <h1>Gerenciar Curso</h1>

    <div class="mt-2">
        <a href="/cursos/novo" class="btn btn-outline-dark btn-sm">Novo Curso</a>

        <a href="/cursos/relatorio" target="_blank" class="btn btn-outline-dark btn-sm">Gerar PDF</a>
    </div>

    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Periodo</th>
                <th>Professor</th>
                <th>Laboratorio</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
            // if(isset($alunos) && sizeOf($alunos) > 0){
            foreach ($cursos ?? [] as $curso) {
                echo "
                            <tr>
                                <td>{$curso->id}</td>
                                <td>{$curso->nome}</td>
                                <td>{$curso->periodo}</td>
                                <td>{$curso->professor}</td>
                                <td>{$curso->laboratorio}</td>
                                <td>
                                    <a href='/alunos/editar?id={$curso->id}' class='btn btn-outline-warning btn-sm'>Editar</a>
                                    <a href='/alunos/excluir?id={$curso->id}' class='btn btn-outline-danger btn-sm'>Excluir</a>
                                </td>
                            </tr>
                        ";
            }
            // }
            ?>
        </tbody>
    </table>
</section>